import {Images} from '@theme';

export const DATA = [
  {
    id: 0,
    isSelect: false,
    title: 'Politics',
    img: Images.welcomepolitics,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverzoo,
    shareTitle: 'Fatherhood',
    shareByTitle: 'by Christopher Wilson',
    recentImage: Images.discoverfatal,
    recentTitle: 'The Fatal Tree',
    recentByTitle: 'by Jake Amott',
  },
  {
    id: 1,
    isSelect: false,
    title: 'History',
    img: Images.welcomehistory,
    place: 'GJ',
    bookImg: Images.discoveonce,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'by Christopher Wilson',
    recentImage: Images.discoverdayfour,
    recentTitle: 'The Fatal Tree',
    recentByTitle: 'by Jake Amott',
  },
  {
    id: 2,
    isSelect: false,
    title: 'Science',
    img: Images.welcomescience,
    place: 'MH',
    bookImg: Images.discoverqueen1,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'by Christopher Wilson',
    recentImage: Images.discoverfatal,
    recentTitle: 'The Fatal Tree',
    recentByTitle: 'by Jake Amott',
  },
  {
    id: 3,
    isSelect: false,
    title: 'Law',
    img: Images.welcomelaw,
    place: 'DL',
    bookImg: Images.discoverandy,
    shareImge: Images.discoverandy,
    shareTitle: 'Fatherhood',
    shareByTitle: 'by Christopher Wilson',
    recentImage: Images.discoverfatal,
    recentTitle: 'The Fatal Tree',
    recentByTitle: 'by Jake Amott',
  },
  {
    id: 4,
    isSelect: false,
    title: 'Food',
    img: Images.welcomefood,
    place: 'GJ',
    bookImg: Images.discoverlife,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'by Christopher Wilson',
    recentImage: Images.discoverfatal,
    recentTitle: 'The Fatal Tree',
    recentByTitle: 'by Jake Amott',
  },
  {
    id: 5,
    isSelect: false,
    title: 'Medical',
    img: Images.welcomemedical,
    place: 'DL',
    bookImg: Images.discoverfate,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'by Christopher Wilson',
    recentImage: Images.discoverfatal,
    recentTitle: 'The Fatal Tree',
    recentByTitle: 'by Jake Amott',
  },
];
