export const Images = {
  homebook: require('./images/book.png'),
  homeline: require('./images/line.png'),
  startfirst: require('./images/first.png'),
  startsecond: require('./images/second.png'),
  startthird: require('./images/third.png'),
  welcomehistory: require('./images/history.png'),
  welcomescience: require('./images/science.png'),
  welcomelaw: require('./images/law.png'),
  welcomefood: require('./images/food.png'),
  welcomemedical: require('./images/medical.png'),
  welcomedesign: require('./images/design.png'),
  welcomesport: require('./images/sport.png'),
  tabdiscover: require('./images/discover.png'),
  tabdiscoverclick: require('./images/discover-pink.png'),
  tablibrary: require('./images/library.png'),
  tablibrarypink: require('./images/library-pink.png'),
  tabwishlist: require('./images/heart.png'),
  tabwishlistpink: require('./images/heart-pink.png'),
  tabstore: require('./images/store.png'),
  tabstorepink: require('./images/store-pink.png'),
  tabprofile: require('./images/profile.png'),
  tabprofilepink: require('./images/profile-pink.png'),
};
