import {Images} from '@theme';

export const DATA = [
  {
    id: 0,
    isSelect: false,
    title: 'Politics',
    img: Images.welcomepolitics,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 1,
    isSelect: false,
    title: 'History',
    img: Images.welcomehistory,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 2,
    isSelect: false,
    title: 'Science',
    img: Images.welcomescience,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 3,
    isSelect: false,
    title: 'Law',
    img: Images.welcomelaw,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 4,
    isSelect: false,
    title: 'Food',
    img: Images.welcomefood,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 5,
    isSelect: false,
    title: 'Medical',
    img: Images.welcomemedical,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 6,
    isSelect: false,
    title: 'Design',
    img: Images.welcomedesign,
    place: 'HR',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 7,
    isSelect: false,
    title: 'Culture',
    img: Images.welcomeculture,
    place: 'HR',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 8,
    isSelect: false,
    title: 'Sports',
    img: Images.welcomesport,
    place: 'HR',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 9,
    isSelect: false,
    title: 'Politics',
    img: Images.welcomepolitics,
    place: 'HR',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 10,
    isSelect: false,
    title: 'History',
    img: Images.welcomehistory,
    place: 'HR',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 11,
    isSelect: false,
    title: 'Science',
    img: Images.welcomescience,
    place: 'HR',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 12,
    isSelect: false,
    title: 'Law',
    img: Images.welcomelaw,
    place: 'PN',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 13,
    isSelect: false,
    title: 'Food',
    img: Images.welcomefood,
    place: 'PN',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 14,
    isSelect: false,
    title: 'Medical',
    img: Images.welcomemedical,
    place: 'PN',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 15,
    isSelect: false,
    title: 'Design',
    img: Images.welcomedesign,
    place: 'PN',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 16,
    isSelect: false,
    title: 'Culture',
    img: Images.welcomeculture,
    place: 'PN',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 17,
    isSelect: false,
    title: 'Sports',
    img: Images.welcomesport,
    place: 'PN',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
];
