import {Images} from '@theme';

export const DATA = [
  {
    id: 0,
    isSelect: false,
    title: 'Politics',
    img: Images.welcomepolitics,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 1,
    isSelect: false,
    title: 'History',
    img: Images.welcomehistory,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 2,
    isSelect: false,
    title: 'Science',
    img: Images.welcomescience,
    place: 'MH',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 3,
    isSelect: false,
    title: 'Law',
    img: Images.welcomelaw,
    place: 'DL',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 4,
    isSelect: false,
    title: 'Food',
    img: Images.welcomefood,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 5,
    isSelect: false,
    title: 'Medical',
    img: Images.welcomemedical,
    place: 'DL',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 6,
    isSelect: false,
    title: 'Design',
    img: Images.welcomedesign,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 7,
    isSelect: false,
    title: 'Culture',
    img: Images.welcomeculture,
    place: 'GJ',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
  {
    id: 8,
    isSelect: false,
    title: 'Sports',
    img: Images.welcomesport,
    place: 'MH',
    bookImg: Images.discoverqueen,
    shareImge: Images.discoverland,
    shareTitle: 'Fatherhood',
    shareByTitle: 'Christopher Wilson',
  },
];
